version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - ./influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  epb-usage-exporter:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env

